# render.yaml
services:
  - type: web
    name: flask-backend
    env: python
    plan: free
    repo: https://github.com/Sayyam-Karnavat/algorand_python_code_compiler/tree/main/server
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - fromDotEnv: true
